trigger:
  - master

resources:
  - repo: self

variables:
  # Buffalo
  BUFFALO_VERSION: "0.14.6"

  # Go
  GOVERSION: "1.12"
  GOROOT: '/usr/local/go$(GOVERSION)'
  GOPATH: '/home/vsts/go'

  # Container registry service connection established during pipeline creation
  dockerRegistryServiceConnection: 'a041da97-3f29-4781-a417-751b98eb7903'
  imageRepository: 'italypaleale/smplatform'
  containerRegistry: 'hub.docker.com'
  dockerfilePath: '$(Build.SourcesDirectory)/container/Dockerfile-copy-binary'
  dockerTag: '$(Build.BuildNumber)'
  testDockerfilePath: '$(Build.SourcesDirectory)/container/Dockerfile-test'
  testImageRepository: 'smplatform-test'

stages:
  - stage: build
    displayName: Build SMPlatform artifacts
    jobs:
      - job: build
        displayName: Build artifacts for Linux (amd64, arm64, armhf)
        pool:
          vmImage: ubuntu-16.04
        steps:
          # Install required packages
          - script: |
              sudo apt-get update
              sudo apt-get install -y \
                build-essential \
                crossbuild-essential-armhf \
                crossbuild-essential-arm64 \
                autoconf \
                libtool \
                cmake \
                pkg-config \
                git \
                automake \
                autogen \
                ca-certificates \
                clang \
                llvm-dev \
                libtool \
                libxml2-dev \
                uuid-dev \
                libssl-dev \
                swig \
                patch \
                make \
                xz-utils \
                cpio \
                sqlite
            displayName: "Install required packages"
          # Set up go environment and Buffalo
          - script: |
              # Add to GOBIN to PATH
              echo '##vso[task.prependpath]$(GOBIN)'
              echo '##vso[task.prependpath]$(GOROOT)/bin'
              # Fetch Buffalo's binary
              cd /tmp
              wget https://github.com/gobuffalo/buffalo/releases/download/v$(BUFFALO_VERSION)/buffalo_$(BUFFALO_VERSION)_linux_amd64.tar.gz
              tar -xvzf buffalo_$(BUFFALO_VERSION)_linux_amd64.tar.gz
              sudo mv buffalo /usr/local/bin/buffalo
            displayName: "Set up go environment and Buffalo"
          # Fetch go dependencies
          - script: |
              # App's dependencies
              GO111MODULE=on go get
            displayName: "Fetch go dependencies"
          # Build amd64
          - script: |
              BUILD_ID=$(Build.BuildNumber)
              BUILD_TIME=$(date -u +'%Y-%m-%dT%H:%M:%S')
              COMMIT_HASH=$(git log --pretty=format:'%h' -n 1)

              GO111MODULE=on \
                buffalo build \
                  --environment production \
                  --ldflags "-X smplatform/buildinfo.BuildID=$BUILD_ID -X smplatform/buildinfo.BuildTime=$BUILD_TIME -X smplatform/buildinfo.CommitHash=$COMMIT_HASH" \
                  --output bin/smplatform_linux_amd64
            displayName: "Build amd64"
          # Build arm64
          # Only run on master
          - script: |
              BUILD_ID=$(Build.BuildNumber)
              BUILD_TIME=$(date -u +'%Y-%m-%dT%H:%M:%S')
              COMMIT_HASH=$(git log --pretty=format:'%h' -n 1)

              CC=aarch64-linux-gnu-gcc-5 \
              CXX=aarch64-linux-gnu-g++-5 \
              GO111MODULE=on \
              GOOS=linux \
              GOARCH=arm64 \
              CGO_ENABLED=1 \
                buffalo build \
                  --environment production \
                  --ldflags "-X smplatform/buildinfo.BuildID=$BUILD_ID -X smplatform/buildinfo.BuildTime=$BUILD_TIME -X smplatform/buildinfo.CommitHash=$COMMIT_HASH" \
                  --output bin/smplatform_linux_arm64
            displayName: "Build arm64"
            condition: "and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))"
          # Build armhf
          # Only run on master
          - script: |
              BUILD_ID=$(Build.BuildNumber)
              BUILD_TIME=$(date -u +'%Y-%m-%dT%H:%M:%S')
              COMMIT_HASH=$(git log --pretty=format:'%h' -n 1)

              CC=arm-linux-gnueabihf-gcc-5 \
              CXX=arm-linux-gnueabihf-g++-5 \
              GO111MODULE=on \
              GOOS=linux \
              GOARCH=arm \
              GOARM=7 \
              CGO_ENABLED=1 \
                buffalo build \
                  --environment production \
                  --ldflags "-X smplatform/buildinfo.BuildID=$BUILD_ID -X smplatform/buildinfo.BuildTime=$BUILD_TIME -X smplatform/buildinfo.CommitHash=$COMMIT_HASH" \
                  --output bin/smplatform_linux_armhf
            displayName: "Build armhf"
            #condition: "and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))"
          # Copy binaries to the artifacts staging directory
          - task: CopyFiles@2
            displayName: Copy binaries to the artifacts staging directory
            inputs:
              sourceFolder: 'bin/'
              contents: '**/*'
              targetFolder: '$(Build.ArtifactStagingDirectory)'
          # Publish binaries as artifacts
          - task: PublishBuildArtifacts@1
            displayName: 'Publish build artifacts'
            inputs:
              artifactName: drop

  # Build Docker container and run test for amd64
  - stage: amd64
    displayName: Containerize and test on amd64
    dependsOn: build
    jobs:
      - job: amd64
        displayName: Containerize and test on amd64
        pool:
          vmImage: ubuntu-16.04
        steps:
          # Download build artifacts from previous stage
          - task: DownloadBuildArtifacts@0
            displayName: Download build artifacts
            inputs:
              buildType: current
              artifactName: drop
              itemPattern: 'drop/**'
              downloadPath: 'bin/'
          - script: |
              pwd
              ls -al
              ls -al bin
          # Build Docker image
          - task: Docker@2
            displayName: Build Docker image
            inputs:
              command: build
              buildContext: $(Build.SourcesDirectory)
              repository: $(imageRepository)
              dockerfile: $(dockerfilePath)
              containerRegistry: $(dockerRegistryServiceConnection)
              arguments: |
                --build-arg ARCH=amd64
              tags: |
                latest
                $(dockerTag)
          # Build Docker test image
          - script: |
              docker build \
                -f $(testDockerfilePath) \
                -t $(testImageRepository) \
                $(Build.SourcesDirectory)/e2e-test
            displayName: Build Docker test image
          # Run end-to-end tests
          - script: |
              docker run \
                --rm \
                -v $(pwd)/e2e-test/container_etc:/etc/smplatform \
                -e "AZURE_STORAGE_SAS_TOKEN=$(AZURE_STORAGE_SAS_TOKEN)" \
                -e "AZURE_CLIENT_SECRET=$(AZURE_CLIENT_SECRET)" \
                -e "NODE_URL=smplatform.local:3000" \
                -e "NGINX_URL=smplatform.local" \
                --add-host "smplatform.local:127.0.0.1" \
                $(testImageRepository)
            displayName:  Run end-to-end tests
          # Push Docker image to container registry
          # Only run on master
          - task: Docker@2
            condition: "and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))"
            displayName: Push Docker image to container registry
            inputs:
              command: push
              repository: $(imageRepository)
              containerRegistry: $(dockerRegistryServiceConnection)
              tags: |
                latest
                $(dockerTag)
