development:
  dialect: sqlite3
  database: /app/smplatform_development.sqlite

test:
  dialect: sqlite3
  database: /app/smplatform_test.sqlite

production:
  dialect: sqlite3
  database: /etc/smplatform/data.db
