# Authorization for managing the node
auth:
  # Authorize with a pre-shared key
  psk:
    # Enabled
    enabled: yes
    # Key
    # Can also be passed with environmental variable AUTH_KEY
    key: "hello world"

  # Authorize with an OAuth 2.0 access token issued by Azure AD
  azureAD:
    # Enabled
    enabled: yes
    # Tenant ID of the application used to authenticate users
    # Can also be passed with environmental variable AUTH_AZUREAD_TENANT_ID
    tenantId: "1ea3c9a2-b58b-48c7-b5ce-ca311c3c1196"    
    # Client ID of the application used to authenticate users
    # Can also be passed with environmental variable AUTH_AZUREAD_CLIENT_ID
    # DEV NOTE: in development, we're using the same app for both Azure AD authentication and as an Azure Service Principal. Not recommended in production, however
    clientId: "478f8d4c-d845-478d-bff9-63a0258ee5b1"

# Encryption key for secrets. Must be a base64-encoded (standard encoding) key of 128-bit (16 byte).
# Generate it with a command like `openssl rand 16 | base64`
# Can also be passed with environmental variable SECRETS_ENCRYPTION_KEY
secretsEncryptionKey: "aQZg30UrCUgu0TfdNvIeLg=="

# Port the server is listening on (must be a string)
# Defaults to 2265 if not set
# Can also be passed with environmental variable PORT
port: "2265"

# State storage configuration
state:
  # Where to store state - can be "file" or "etcd"
  # Can also be passed with environmental variable STATE_STORE
  store: "file"

  # Configuration for when "store" is "file"
  file:
    # File containing the state persistently stored on disk
    # Can also be passed with environmental variable STATE_FILE_PATH
    path: "/etc/statiko/state.json"

  # Configuration for when "store" is "etcd"
  etcd:
    # Prefix for keys used by statiko in etcd
    # Can also be passed with environmental variable STATE_ETCD_KEY_PREFIX
    keyPrefix: "/statiko"
    # Timeout in ms
    # Can also be passed with environmental variable STATE_ETCD_TIMEOUT
    timeout: 15000
    # List of etcd node addresses to connect to, comma-separated
    # Can also be passed with environmental variable STATE_ETCD_ADDRESS
    address: "http://localhost:2379,http://etcd:2379"

# Configuration for the nginx webserver
nginx:
  # Path where the nginx config is stored
  configPath: "/etc/nginx/"
  # User running nginx
  # Can also be passed with environmental variable NGINX_USER
  user: "www-data"
  # Shell commands to start/stop/restart(reload) nginx
  commands:
    # Can also be passed with environmental variable NGINX_START
    start: "service nginx start"
    # Can also be passed with environmental variable NGINX_STOP
    stop: "service nginx stop"
    # Can also be passed with environmental variable NGINX_RESTART
    restart: "service nginx status > /dev/null && service nginx reload || service nginx restart"
    # Can also be passed with environmental variable NGINX_STATUS
    status: "service nginx status > /dev/null && echo 1 || echo 0"

# Path
# Use a folder inside /mnt (e.g. /mnt/data/) for Azure VMs to leverage the locally-attached SSD
# Can also be passed with environmental variable APP_ROOT
appRoot: "/data/"

# Azure configuration
azure:
  # Service Principal details
  sp:
    # Can also be passed with environmental variable AZURE_TENANT_ID
    tenantId: "1ea3c9a2-b58b-48c7-b5ce-ca311c3c1196"
    # Can also be passed with environmental variable AZURE_CLIENT_ID
    clientId: "478f8d4c-d845-478d-bff9-63a0258ee5b1"
    # Can also be passed with environmental variable AZURE_CLIENT_SECRET
    clientSecret: ""

  # Azure Storage
  storage:
    # Storage account name
    # Can also be passed with environmental variable AZURE_STORAGE_ACCOUNT
    account: "statikocistorage"
    # Container name
    # Can also be passed with environmental variable AZURE_STORAGE_APPS_CONTAINER
    appsContainer: "apps"

  # Azure Key Vault
  keyVault:
    # Name of the Key Vault
    # Can also be passed with environmental variable AZURE_KEYVAULT_NAME
    name: "statiko-ci-akv"

    # Code signing key
    codesignKey:
      # Name of the code signing key inside the Key Vault
      # Can also be passed with environmental variable CODESIGN_KEY_NAME
      name: "codesign"
      # Version of the code signing key inside the Key Vault
      # Defaults to the latest one if null
      # Can also be passed with environmental variable CODESIGN_KEY_VERSION
      version: null

# TLS
tls:
  # Diffie-Hellman parameters used by all TLS-enabled sites
  dhparams: "/etc/statiko/dhparams.pem"
  node:
    # Using TLS is strongly recommended
    enabled: yes
    certificate: "/etc/statiko/node-public.crt"
    key: "/etc/statiko/node-private.key"

# Node name (optional; will default to the hostname)
# Can also be passed with environmental variable NODE_NAME
nodeName: "e2e-test"

# Name for the manifest file inside app bundles
manifestFile: "_statiko.yaml"

# Set to true to require all deployed apps to be cryptographically signed
disallowUnsignedApps: false

# Notifications to admin
notifications:
  # Notification method; "webhook" is the only supported value for now
  # Can also be passed with environmental variable NOTIFICATIONS_METHOD
  method: "off"
  # Configuration for when method is "webhook"
  webhook:
    # URL to invoke
    # Message is a POST request containing payload `{"<payloadKey>": "message"}`, where `<payloadKey>` is defined below
    # Can also be passed with environmental variable NOTIFICATIONS_WEBHOOK_URL
    url: ""
    # Key for the message in the JSON object
    # If you're using IFTTT for the webhook, set this to `value1`; other webhook services might support different values or custom ones
    # Can also be passed with environmental variable NOTIFICATIONS_WEBHOOK_PAYLOAD_KEY
    payloadKey: "value1"
