# Authorization for managing the node
auth:
  # Authorize with a pre-shared key
  psk:
    # Enabled
    enabled: yes
    # Key
    # Can also be passed with environmental variable AUTH_KEY
    key: "hello world"

  # Authorize with an OAuth 2.0 access token issued by Azure AD
  azureAD:
    # Enabled
    enabled: yes
    # Tenant ID of the application used to authenticate users
    # Can also be passed with environmental variable AUTH_AZUREAD_TENANT_ID
    tenantId: "1ea3c9a2-b58b-48c7-b5ce-ca311c3c1196"    
    # Client ID of the application used to authenticate users
    # Can also be passed with environmental variable AUTH_AZUREAD_CLIENT_ID
    # DEV NOTE: in development, we're using the same app for both Azure AD authentication and as an Azure Service Principal. Not recommended in production, however
    clientId: "478f8d4c-d845-478d-bff9-63a0258ee5b1"

# Encryption key for secrets. Must be a base64-encoded (standard encoding) key of 128-bit (16 byte).
# Generate it with a command like `openssl rand 16 | base64`
# Can also be passed with environmental variable SECRETS_ENCRYPTION_KEY
secretsEncryptionKey: "aQZg30UrCUgu0TfdNvIeLg=="

# Azure configuration
azure:
  # Service Principal details
  sp:
    # Can also be passed with environmental variable AZURE_TENANT_ID
    tenantId: "1ea3c9a2-b58b-48c7-b5ce-ca311c3c1196"
    # Can also be passed with environmental variable AZURE_CLIENT_ID
    clientId: "478f8d4c-d845-478d-bff9-63a0258ee5b1"
    # Can also be passed with environmental variable AZURE_CLIENT_SECRET
    clientSecret: ""

  # Azure Storage
  storage:
    # Storage account name
    # Can also be passed with environmental variable AZURE_STORAGE_ACCOUNT
    account: "statikocistorage"

  # Azure Key Vault
  keyVault:
    # Name of the Key Vault
    # Can also be passed with environmental variable AZURE_KEYVAULT_NAME
    name: "statiko-ci-akv"

    # Code signing key
    codesignKey:
      # Name of the code signing key inside the Key Vault
      # Can also be passed with environmental variable CODESIGN_KEY_NAME
      name: "codesign"

# Node name (optional; will default to the hostname)
# Can also be passed with environmental variable NODE_NAME
nodeName: "e2e-test"
