# Authorization for managing the node
auth:
  # Authorize with a pre-shared key
  psk:
    # Enabled
    enabled: yes
    # Key
    # Can also be passed with environmental variable AUTH_KEY
    key: "hello world"

  # Authorize with an OAuth 2.0 access token issued by Azure AD
  # See the "azure.app" dictionary below for app's details
  azureAD:
    # Enabled
    enabled: yes

# Port the server is listening on (must be a string)
# Defaults to 2265 if not set
# Can also be passed with environmental variable PORT
port: "2265"

# State storage configuration
state:
  # Where to store state - can be "file" or "etcd"
  # Can also be passed with environmental variable STATE_STORE
  store: "file"

  # Configuration for when "store" is "file"
  file:
    # File containing the state persistently stored on disk
    # Can also be passed with environmental variable STATE_FILE_PATH
    path: "/etc/smplatform/state.json"

  # Configuration for when "store" is "etcd"
  etcd:
    # Key where the state is stored in etcd
    # Can also be passed with environmental variable STATE_ETCD_KEY
    key: "smplatform"
    # Timeout in ms
    # Can also be passed with environmental variable STATE_ETCD_TIMEOUT
    timeout: 15000
    # List of etcd node addresses to connect to, comma-separated
    # Can also be passed with environmental variable STATE_ETCD_ADDRESS
    address: "http://localhost:2379,http://etcd:2379"

# Configuration for the nginx webserver
nginx:
  # Path where the nginx config is stored
  configPath: "/etc/nginx/"
  # User running nginx
  # Can also be passed with environmental variable NGINX_USER
  user: "www-data"
  # Shell commands to start/stop/restart(reload) nginx
  commands:
    # Can also be passed with environmental variable NGINX_START
    start: "service nginx start"
    # Can also be passed with environmental variable NGINX_STOP
    stop: "service nginx stop"
    # Can also be passed with environmental variable NGINX_RESTART
    restart: "service nginx status > /dev/null && service nginx reload || service nginx restart"
    # Can also be passed with environmental variable NGINX_STATUS
    status: "service nginx status > /dev/null && echo 1 || echo 0"

# Path
# Use a folder inside /mnt (e.g. /mnt/data/) for Azure VMs to leverage the locally-attached SSD
# Can also be passed with environmental variable APP_ROOT
appRoot: "/data/"

# Azure configuration
azure:
  # App / Service Principal details
  app:
    # Can also be passed with environmental variable AZURE_TENANT_ID
    tenantId: "de366b7a-4861-4e17-b67b-8e3cdd4f2408"
    # Can also be passed with environmental variable AZURE_CLIENT_ID
    clientId: "797c905d-b49a-4ddf-9425-80e39b3c0a19"
    # Can also be passed with environmental variable AZURE_CLIENT_SECRET
    clientSecret: ""

  # Azure Storage
  storage:
    # Storage account name
    # Can also be passed with environmental variable AZURE_STORAGE_ACCOUNT
    account: "smplatformcistorage"
    # Storage account key
    # Can also be passed with environmental variable AZURE_STORAGE_KEY
    key: ""
    # Container name
    # Can also be passed with environmental variable AZURE_STORAGE_APPS_CONTAINER
    appsContainer: "apps"

  # Azure Key Vault
  keyVault:
    # Name of the Key Vault
    # Can also be passed with environmental variable AZURE_KEYVAULT_NAME
    name: "smplatform-ci-akv"

    # Code signing key
    codesignKey:
      # Name of the code signing key inside the Key Vault
      # Can also be passed with environmental variable CODESIGN_KEY_NAME
      name: "codesign"
      # Version of the code signing key inside the Key Vault
      # Defaults to the latest one if null
      # Can also be passed with environmental variable CODESIGN_KEY_VERSION
      version: null

# TLS
tls:
  # Diffie-Hellman parameters used by all TLS-enabled sites
  dhparams: "/etc/smplatform/dhparams.pem"
  node:
    # Using TLS is strongly recommended
    enabled: yes
    certificate: "/etc/smplatform/node-public.crt"
    key: "/etc/smplatform/node-private.key"

# Node name (optional; will default to the hostname)
# Can also be passed with environmental variable NODE_NAME
nodeName: "e2e-test"

# Name for the manifest file inside app bundles
manifestFile: "_smplatform.yaml"

# Set to true to require all deployed apps to be cryptographically signed
disallowUnsignedApps: true

# Notifications to admin
notifications:
  # Notification method; "webhook" is the only supported value for now
  # Can also be passed with environmental variable NOTIFICATIONS_METHOD
  method: "off"
  # Configuration for when method is "webhook"
  webhook:
    # URL to invoke
    # Message is a POST request containing payload `{"value1": "message"}`
    # Can also be passed with environmental variable NOTIFICATIONS_WEBHOOK_URL
    url: ""
