basePath: '{{.BasePath}}'
definitions:
  actions.Message:
    properties:
      message:
        type: string
    type: object
  actions.NodeApps:
    properties:
      appName:
        type: string
      appVersion:
        type: string
      domain:
        type: string
      id:
        type: string
      updated:
        type: string
    type: object
  actions.NodeStatus:
    properties:
      apps:
        items:
          $ref: '#/definitions/actions.NodeApps'
        type: array
      health:
        items:
          $ref: '#/definitions/actions.SiteHealth'
        type: array
    type: object
  actions.SiteHealth:
    properties:
      domain:
        type: string
      error:
        type: string
      size:
        type: integer
      status:
        type: integer
      time:
        type: string
    type: object
host: '{{.Host}}'
info:
  contact: {}
  description: '{{.Description}}'
  license: {}
  title: Platform node APIs
  version: "1.0"
paths:
  /adopt:
    post:
      description: |-
        The Platform Controller node can invoke this method to "adopt" the node.
        This action is destructive as will delete all existing sites and applications, and reset the node to a clean state.
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/actions.Message'
            type: object
        "500": {}
      summary: Tells the application to adopt the node, initializing it to a clean
        state
  /site:
    post:
      consumes:
      - application/json
      description: Creates a new site in the local web server and configures it with
        the default app
      parameters:
      - description: Domain name
        in: body
        name: domain
        required: true
        schema:
          $ref: '#/definitions/string'
          type: object
      - description: TLS Certificate name in the Key Vault
        in: body
        name: tlsCertificate
        required: true
        schema:
          $ref: '#/definitions/string'
          type: object
      produces:
      - application/json
      responses:
        "500": {}
      summary: Creates a new site
  /status:
    get:
      description: |-
        Returns an object listing the sites currently running and the apps deployed.
        This route is designed and optimized for periodic health-checks too.
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/actions.NodeStatus'
            type: array
      summary: Returns the status and health of the node
swagger: "2.0"
