# This pipeline runs the Continuous Integration tasks
# Builds statiko for amd64 only, creates the Docker container and the test container, and runs the unit tests

# Required secrets:
# - DOCKER_PASSWORD password for Docker Hub
# - AZURE_CLIENT_SECRET secret for the Azure Service principal

name: Continuous Integration

on:
  pull_request:
    branches: [master]
  push:
    branches: [master]

env:
  BUILDER_IMAGE: 'golang:1.13-alpine'
  DOCKER_USERNAME: 'italypaleale'
  DOCKER_REPO: 'docker.io/statiko/statiko'
  
jobs:

  ci:
    name: Continuous Integration
    runs-on: ubuntu-18.04
    steps:

    - name: Check out code
      uses: actions/checkout@v2
    
    # Build Statiko
    - name: Define build info
      run: |
        BUILD_ID="canary"
        BUILD_TIME=$(date -u +'%Y-%m-%dT%H:%M:%S')
        COMMIT_HASH=$(echo $GITHUB_SHA | head -c 7)
        TAG="ci-$(date -u +'%Y%m%d%H%M%S')"
        echo ::set-env name=BUILD_ID::$BUILD_ID
        echo ::set-env name=BUILD_TIME::$BUILD_TIME
        echo ::set-env name=COMMIT_HASH::$COMMIT_HASH
        echo ::set-env name=TAG::$TAG

    - name: Build Statiko
      run: |
        mkdir -p .bin

        # Build using Docker
        docker run \
          --rm \
          -v "$PWD":/usr/src/myapp \
          -w /usr/src/myapp \
          ${{env.BUILDER_IMAGE}} \
            sh -c '
              echo "###\nFetching modules\n"
              GO111MODULE=on \
                go get

              echo "\n###\nBuilding amd64\n"
              # Disable CGO so the binary is fully static
              CGO_ENABLED=0 \
              GOOS=linux \
              GOARCH=amd64 \
              GO111MODULE=on \
                go build \
                  -v \
                  -ldflags "-X github.com/ItalyPaleAle/statiko/buildinfo.ENV=production -X github.com/ItalyPaleAle/statiko/buildinfo.BuildID=${{env.BUILD_ID}} -X github.com/ItalyPaleAle/statiko/buildinfo.BuildTime=${{env.BUILD_TIME}} -X github.com/ItalyPaleAle/statiko/buildinfo.CommitHash=${{env.COMMIT_HASH}}" \
                  -o .bin/statiko_linux_amd64
              
              echo "\n###\nBuilding amd64 test binary\n"
              # Disable CGO so the binary is fully static
              CGO_ENABLED=0 \
              GOOS=linux \
              GOARCH=amd64 \
              GO111MODULE=on \
                go test \
                -v \
                -coverpkg=github.com/ItalyPaleAle/statiko/... \
                -c \
                -tags e2etests \
                -ldflags "-X github.com/ItalyPaleAle/statiko/buildinfo.ENV=production -X github.com/ItalyPaleAle/statiko/buildinfo.BuildID=${{env.BUILD_ID}} -X github.com/ItalyPaleAle/statiko/buildinfo.BuildTime=${{env.BUILD_TIME}} -X github.com/ItalyPaleAle/statiko/buildinfo.CommitHash=${{env.COMMIT_HASH}}" \
                -o .bin/statiko_linux_amd64.test
              '
        echo "\n###\nCompilation done\n"
        ls -al .bin
    
    # Build Docker images
    - name: Build Docker image
      run: |
        # Use the "latest" tag here
        docker build \
          --tag "${{env.DOCKER_REPO}}:latest" \
          --build-arg TARGETARCH=amd64 \
          --build-arg BUILD_ID=${{env.BUILD_ID}} \
          --build-arg BUILD_TIME=${{env.BUILD_TIME}} \
          --build-arg COMMIT_HASH=${{env.COMMIT_HASH}} \
          -f .container/agent/Dockerfile \
          .
    - name: Build Docker test image
      run: |
        mkdir -p .e2e-test/.bin
        cp .bin/*.test .e2e-test/.bin
        docker build \
          --tag statiko-test \
          --build-arg TARGETARCH=amd64 \
          -f .container/e2e-test/Dockerfile \
          .e2e-test
    # Run tests
    - name: Run end-to-end tests
      run: |
        docker run \
          --rm \
          -v "$PWD"/.e2e-test/container_etc:/etc/statiko \
          -v "$PWD"/.e2e-test/results:/results \
          -e "AZURE_CLIENT_SECRET=${{ secrets.AZURE_CLIENT_SECRET }}" \
          -e "NODE_URL=statiko.local:2265" \
          -e "NGINX_URL=statiko.local" \
          --add-host "statiko.local:127.0.0.1" \
          statiko-test
    - name: Print logs
      # This step always runs, even if the tests failed
      if: always()
      run: |
        echo "### Test stdout ###\n"
        cat .e2e-test/results/stdout || echo "File does not exist"
        echo "\n\n### Test stderr ###\n"
        cat .e2e-test/results/stderr || echo "File does not exist"
    - name: Convert coverage report
      run: |
        docker run \
          --rm \
          -v "$PWD":/usr/src/myapp \
          -w /usr/src/myapp \
          golang:1.13-alpine \
            sh -c '
              echo "###\nFetching utilities\n"
              go get github.com/axw/gocov/gocov
              go get github.com/axw/gocov/...
              go get github.com/matm/gocov-html
              go get github.com/AlekSi/gocov-xml

              echo "###\nConverting coverage reports\n"
              gocov convert .e2e-test/results/coverage.out | gocov-xml > .e2e-test/results/coverage.xml
              gocov convert .e2e-test/results/coverage.out | gocov-html > .e2e-test/results/coverage.html
              '
    - name: Publish results and coverage
      # This step always runs, even if the tests failed
      if: always()
      uses: actions/upload-artifact@v1
      with:
        name: tests
        path: .e2e-test/results

    # Publish artifacts
    - name: Publish binaries as artifacts
      uses: actions/upload-artifact@v1
      with:
        name: bin
        path: .bin

    # Login to Docker Hub
    - name: Login to Docker Hub
      env:
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      run: |
        echo "${DOCKER_PASSWORD}" | docker login --username "${{env.DOCKER_USERNAME}}" --password-stdin

    # Publish Docker image
    - name: Publish Docker CI image
      run: |
        # Add the tags before publishing, as we won't be publishing "latest"
        docker tag ${{env.DOCKER_REPO}}:latest ${{env.DOCKER_REPO}}:${{env.TAG}}
        docker tag ${{env.DOCKER_REPO}}:latest ${{env.DOCKER_REPO}}:canary

        # Publish the images
        docker push ${{env.DOCKER_REPO}}:${{env.TAG}}
        docker push ${{env.DOCKER_REPO}}:canary
